package org.wa9nnn.fdcluster.rig

import org.specs2.matcher.DataTables
import org.specs2.mock.Mockito
import org.specs2.mutable.Specification
import org.wa9nnn.fdcluster.rig.MockSocketAdapter.expectedCaps
import org.wa9nnn.fdcluster.rig.RigIo.defaultPort

class RigIoSpec extends Specification with DataTables with Mockito {
  sequential
  "RigIoSpec" >> {

    "hostPortParse" >> {
      val defaultPort = 4532
      "in" || "host" | "port" |
        "www.u505.com:4532" !! "www.u505.com" ! defaultPort |
        "192.168.0.139:4532" !! "192.168.0.139" ! defaultPort |
        "192.168.0.139" !! "192.168.0.139" ! defaultPort |> { (in, expectedHost, expectedPort) =>
        val (host, port) = SocketAdapter.hostPortParse(in, defaultPort)
        host must beEqualTo(expectedHost)
        port must beEqualTo(expectedPort)
      }
    }

    "socketTests" >> {
      //      val rig = new RigIo(MockSocketAdapter)
      val rig = new RigIo(SocketAdapter("192.168.0.177", defaultPort))


      "caps" >> {
        val caps: Map[String, String] = rig.caps
        val str = caps("Model name")
        caps must contain("Model name")


      }

      "modeAndBandWidth" >> {
        val (mode, bandwidth) = rig.modeAndBandWidth
        mode must beEqualTo("PKTUSB")
        bandwidth must beEqualTo(3600)
      }

      "frequency" >> {
        rig.frequency must beEqualTo(7074000)
      }
    }
  }

}

object MockSocketAdapter extends SocketAdapter {

  override def doOp(command: String): Seq[String] = {
    data(command)
  }

  val expectedCaps = Seq(
    "Caps dump for model: 3078",
    "Model name:	IC-7610",
    "Mfg name:	Icom",
    "Backend version:	20201219.0",
    "Backend copyright:	LGPL",
    "Backend status:	Stable",
    "Rig type:	Transceiver",
    "PTT type:	Rig capable",
    "DCD type:	Rig capable",
    "Port type:	RS-232",
    "Serial speed: 300..115200 bauds, 8N1 ",
    "Write delay: 0mS, timeout 1000mS, 3 retry",
    "Post Write delay: 0mS",
    "Has targetable VFO: N",
    "Has transceive: Y",
    "Announce: 0x0",
    "Max RIT: -9.999kHz/+9.999kHz",
    "Max XIT: -9.999kHz/+9.999kHz",
    "Max IF-SHIFT: -0.0kHz/+0.0kHz",
    "Preamp: 10dB 20dB",
    "Attenuator: 6dB 12dB 18dB",
    "CTCSS: 67.0 69.3 71.9 74.4 77.0 79.7 82.5 85.4 88.5 91.5 94.8 97.4 100.0 103.5 107.2 110.9 114.8 118.8 123.0 127.3 131.8 136.5 141.3 146.2 151.4 156.7 159.8 162.2 165.5 167.9 171.3 173.8 177.3 179.9 183.5 186.2 189.9 192.8 196.6 199.5 203.5 206.5 210.7 218.1 225.7 229.1 233.6 241.8 250.3 254.1 Hz, 50 tones",
    "DCS: None",
    "Get functions: NB COMP VOX TONE TSQL SBKIN FBKIN ANF NR APF MON MN LOCK RIT TUNER XIT DUAL_WATCH ",
    "Set functions: NB COMP VOX TONE TSQL SBKIN FBKIN ANF NR APF MON MN LOCK RIT TUNER XIT DUAL_WATCH ",
    "Extra functions:",
    "Get level: PREAMP(0..0/0) ATT(0..0/0) VOXDELAY(0..20/1) AF(0..0/0) RF(0..0/0) SQL(0..0/0) NR(0..0/0) PBT_IN(0..0/0) PBT_OUT(0..0/0) CWPITCH(300..900/1) RFPOWER(0..0/0) MICGAIN(0..0/0) KEYSPD(6..48/1) COMP(0..0/0) AGC(0..0/0) BKINDL(0..0/0) BAL(0..0/0) VOXGAIN(0..0/0) ANTIVOX(0..0/0) RAWSTR(0..255/0) SWR(0..0/0) ALC(0..0/0) STRENGTH(0..0/0) RFPOWER_METER(0..0/0) COMP_METER(0..0/0) VD_METER(0..0/0) ID_METER(0..0/0) NOTCHF_RAW(0..0/0) MONITOR_GAIN(0..0/0) NB(0..0/0) ",
    "Set level: PREAMP(0..0/0) ATT(0..0/0) VOXDELAY(0..20/1) AF(0..0/0) RF(0..0/0) SQL(0..0/0) NR(0..0/0) PBT_IN(0..0/0) PBT_OUT(0..0/0) CWPITCH(300..900/1) RFPOWER(0..0/0) MICGAIN(0..0/0) KEYSPD(6..48/1) COMP(0..0/0) AGC(0..0/0) BKINDL(0..0/0) BAL(0..0/0) VOXGAIN(0..0/0) ANTIVOX(0..0/0) NOTCHF_RAW(0..0/0) MONITOR_GAIN(0..0/0) NB(0..0/0) ",
    "Extra levels:",
    "Get parameters: ANN(0..0/0) BACKLIGHT(0..0/0) ",
    "Set parameters: ANN(0..0/0) BACKLIGHT(0..0/0) ",
    "Extra parameters:",
    "Mode list: AM CW USB LSB RTTY FM CWR RTTYR PKTLSB PKTUSB PKTFM PKTAM PSK PSKR ",
    "VFO list: Sub Main MEM ",
    "VFO Ops: CPY XCHG FROM_VFO TO_VFO MCL TUNE ",
    "Scan Ops: MEM PRIO PROG DELTA VFO ",
    "Number of banks:	0",
    "Memory name desc size:	0",
    "Memories:",
    "	1..99:   	MEM",
    "	  Mem caps: ",
    "	100..101:   	EDGE",
    "	  Mem caps: ",
    "TX ranges #1 for ITU1:",
    "	1810000 Hz - 2000000 Hz",
    "		VFO list: Sub Main MEM ",
    "		Mode list: AM CW USB LSB RTTY FM CWR RTTYR PKTLSB PKTUSB PKTFM PSK PSKR ",
    "		Antenna list: ANT1 ANT2 ",
    "		Low power: 2 W, High power: 100 W",
    "	3500000 Hz - 3800000 Hz",
    "		VFO list: Sub Main MEM ",
    "		Mode list: AM CW USB LSB RTTY FM CWR RTTYR PKTLSB PKTUSB PKTFM PSK PSKR ",
    "		Antenna list: ANT1 ANT2 ",
    "		Low power: 2 W, High power: 100 W",
    "	7000000 Hz - 7100000 Hz",
    "		VFO list: Sub Main MEM ",
    "		Mode list: AM CW USB LSB RTTY FM CWR RTTYR PKTLSB PKTUSB PKTFM PSK PSKR ",
    "		Antenna list: ANT1 ANT2 ",
    "		Low power: 2 W, High power: 100 W",
    "	10100000 Hz - 10150000 Hz",
    "		VFO list: Sub Main MEM ",
    "		Mode list: AM CW USB LSB RTTY FM CWR RTTYR PKTLSB PKTUSB PKTFM PSK PSKR ",
    "		Antenna list: ANT1 ANT2 ",
    "		Low power: 2 W, High power: 100 W",
    "	14000000 Hz - 14350000 Hz",
    "		VFO list: Sub Main MEM ",
    "		Mode list: AM CW USB LSB RTTY FM CWR RTTYR PKTLSB PKTUSB PKTFM PSK PSKR ",
    "		Antenna list: ANT1 ANT2 ",
    "		Low power: 2 W, High power: 100 W",
    "	18068000 Hz - 18168000 Hz",
    "		VFO list: Sub Main MEM ",
    "		Mode list: AM CW USB LSB RTTY FM CWR RTTYR PKTLSB PKTUSB PKTFM PSK PSKR ",
    "		Antenna list: ANT1 ANT2 ",
    "		Low power: 2 W, High power: 100 W",
    "	21000000 Hz - 21450000 Hz",
    "		VFO list: Sub Main MEM ",
    "		Mode list: AM CW USB LSB RTTY FM CWR RTTYR PKTLSB PKTUSB PKTFM PSK PSKR ",
    "		Antenna list: ANT1 ANT2 ",
    "		Low power: 2 W, High power: 100 W",
    "	24890000 Hz - 24990000 Hz",
    "		VFO list: Sub Main MEM ",
    "		Mode list: AM CW USB LSB RTTY FM CWR RTTYR PKTLSB PKTUSB PKTFM PSK PSKR ",
    "		Antenna list: ANT1 ANT2 ",
    "		Low power: 2 W, High power: 100 W",
    "	28000000 Hz - 29700000 Hz",
    "		VFO list: Sub Main MEM ",
    "		Mode list: AM CW USB LSB RTTY FM CWR RTTYR PKTLSB PKTUSB PKTFM PSK PSKR ",
    "		Antenna list: ANT1 ANT2 ",
    "		Low power: 2 W, High power: 100 W",
    "	50000000 Hz - 54000000 Hz",
    "		VFO list: Sub Main MEM ",
    "		Mode list: AM CW USB LSB RTTY FM CWR RTTYR PKTLSB PKTUSB PKTFM PSK PSKR ",
    "		Antenna list: ANT1 ANT2 ",
    "		Low power: 2 W, High power: 100 W",
    "	1810000 Hz - 2000000 Hz",
    "		VFO list: Sub Main MEM ",
    "		Mode list: AM PKTAM ",
    "		Antenna list: ANT1 ANT2 ",
    "		Low power: 1 W, High power: 30 W",
    "	3500000 Hz - 3800000 Hz",
    "		VFO list: Sub Main MEM ",
    "		Mode list: AM PKTAM ",
    "		Antenna list: ANT1 ANT2 ",
    "		Low power: 1 W, High power: 30 W",
    "	7000000 Hz - 7100000 Hz",
    "		VFO list: Sub Main MEM ",
    "		Mode list: AM PKTAM ",
    "		Antenna list: ANT1 ANT2 ",
    "		Low power: 1 W, High power: 30 W",
    "	10100000 Hz - 10150000 Hz",
    "		VFO list: Sub Main MEM ",
    "		Mode list: AM PKTAM ",
    "		Antenna list: ANT1 ANT2 ",
    "		Low power: 1 W, High power: 30 W",
    "	14000000 Hz - 14350000 Hz",
    "		VFO list: Sub Main MEM ",
    "		Mode list: AM PKTAM ",
    "		Antenna list: ANT1 ANT2 ",
    "		Low power: 1 W, High power: 30 W",
    "	18068000 Hz - 18168000 Hz",
    "		VFO list: Sub Main MEM ",
    "		Mode list: AM PKTAM ",
    "		Antenna list: ANT1 ANT2 ",
    "		Low power: 1 W, High power: 30 W",
    "	21000000 Hz - 21450000 Hz",
    "		VFO list: Sub Main MEM ",
    "		Mode list: AM PKTAM ",
    "		Antenna list: ANT1 ANT2 ",
    "		Low power: 1 W, High power: 30 W",
    "	24890000 Hz - 24990000 Hz",
    "		VFO list: Sub Main MEM ",
    "		Mode list: AM PKTAM ",
    "		Antenna list: ANT1 ANT2 ",
    "		Low power: 1 W, High power: 30 W",
    "	28000000 Hz - 29700000 Hz",
    "		VFO list: Sub Main MEM ",
    "		Mode list: AM PKTAM ",
    "		Antenna list: ANT1 ANT2 ",
    "		Low power: 1 W, High power: 30 W",
    "	50000000 Hz - 54000000 Hz",
    "		VFO list: Sub Main MEM ",
    "		Mode list: AM PKTAM ",
    "		Antenna list: ANT1 ANT2 ",
    "		Low power: 1 W, High power: 30 W",
    "RX ranges #1 for TBD:",
    "	30000 Hz - 60000000 Hz",
    "		VFO list: Sub Main MEM ",
    "		Mode list: AM CW USB LSB RTTY FM CWR RTTYR PKTLSB PKTUSB PKTFM PKTAM PSK PSKR ",
    "		Antenna list: ANT1 ANT2 ",
    "TX ranges #2 for TBD:",
    "	1800000 Hz - 2000000 Hz",
    "		VFO list: Sub Main MEM ",
    "		Mode list: AM CW USB LSB RTTY FM CWR RTTYR PKTLSB PKTUSB PKTFM PSK PSKR ",
    "		Antenna list: ANT1 ANT2 ",
    "		Low power: 2 W, High power: 100 W",
    "	3500000 Hz - 4000000 Hz",
    "		VFO list: Sub Main MEM ",
    "		Mode list: AM CW USB LSB RTTY FM CWR RTTYR PKTLSB PKTUSB PKTFM PSK PSKR ",
    "		Antenna list: ANT1 ANT2 ",
    "		Low power: 2 W, High power: 100 W",
    "	7000000 Hz - 7300000 Hz",
    "		VFO list: Sub Main MEM ",
    "		Mode list: AM CW USB LSB RTTY FM CWR RTTYR PKTLSB PKTUSB PKTFM PSK PSKR ",
    "		Antenna list: ANT1 ANT2 ",
    "		Low power: 2 W, High power: 100 W",
    "	10100000 Hz - 10150000 Hz",
    "		VFO list: Sub Main MEM ",
    "		Mode list: AM CW USB LSB RTTY FM CWR RTTYR PKTLSB PKTUSB PKTFM PSK PSKR ",
    "		Antenna list: ANT1 ANT2 ",
    "		Low power: 2 W, High power: 100 W",
    "	14000000 Hz - 14350000 Hz",
    "		VFO list: Sub Main MEM ",
    "		Mode list: AM CW USB LSB RTTY FM CWR RTTYR PKTLSB PKTUSB PKTFM PSK PSKR ",
    "		Antenna list: ANT1 ANT2 ",
    "		Low power: 2 W, High power: 100 W",
    "	18068000 Hz - 18168000 Hz",
    "		VFO list: Sub Main MEM ",
    "		Mode list: AM CW USB LSB RTTY FM CWR RTTYR PKTLSB PKTUSB PKTFM PSK PSKR ",
    "		Antenna list: ANT1 ANT2 ",
    "		Low power: 2 W, High power: 100 W",
    "	21000000 Hz - 21450000 Hz",
    "		VFO list: Sub Main MEM ",
    "		Mode list: AM CW USB LSB RTTY FM CWR RTTYR PKTLSB PKTUSB PKTFM PSK PSKR ",
    "		Antenna list: ANT1 ANT2 ",
    "		Low power: 2 W, High power: 100 W",
    "	24890000 Hz - 24990000 Hz",
    "		VFO list: Sub Main MEM ",
    "		Mode list: AM CW USB LSB RTTY FM CWR RTTYR PKTLSB PKTUSB PKTFM PSK PSKR ",
    "		Antenna list: ANT1 ANT2 ",
    "		Low power: 2 W, High power: 100 W",
    "	28000000 Hz - 29700000 Hz",
    "		VFO list: Sub Main MEM ",
    "		Mode list: AM CW USB LSB RTTY FM CWR RTTYR PKTLSB PKTUSB PKTFM PSK PSKR ",
    "		Antenna list: ANT1 ANT2 ",
    "		Low power: 2 W, High power: 100 W",
    "	50000000 Hz - 54000000 Hz",
    "		VFO list: Sub Main MEM ",
    "		Mode list: AM CW USB LSB RTTY FM CWR RTTYR PKTLSB PKTUSB PKTFM PSK PSKR ",
    "		Antenna list: ANT1 ANT2 ",
    "		Low power: 2 W, High power: 100 W",
    "	1800000 Hz - 2000000 Hz",
    "		VFO list: Sub Main MEM ",
    "		Mode list: AM PKTAM ",
    "		Antenna list: ANT1 ANT2 ",
    "		Low power: 1 W, High power: 30 W",
    "	3500000 Hz - 4000000 Hz",
    "		VFO list: Sub Main MEM ",
    "		Mode list: AM PKTAM ",
    "		Antenna list: ANT1 ANT2 ",
    "		Low power: 1 W, High power: 30 W",
    "	7000000 Hz - 7300000 Hz",
    "		VFO list: Sub Main MEM ",
    "		Mode list: AM PKTAM ",
    "		Antenna list: ANT1 ANT2 ",
    "		Low power: 1 W, High power: 30 W",
    "	10100000 Hz - 10150000 Hz",
    "		VFO list: Sub Main MEM ",
    "		Mode list: AM PKTAM ",
    "		Antenna list: ANT1 ANT2 ",
    "		Low power: 1 W, High power: 30 W",
    "	14000000 Hz - 14350000 Hz",
    "		VFO list: Sub Main MEM ",
    "		Mode list: AM PKTAM ",
    "		Antenna list: ANT1 ANT2 ",
    "		Low power: 1 W, High power: 30 W",
    "	18068000 Hz - 18168000 Hz",
    "		VFO list: Sub Main MEM ",
    "		Mode list: AM PKTAM ",
    "		Antenna list: ANT1 ANT2 ",
    "		Low power: 1 W, High power: 30 W",
    "	21000000 Hz - 21450000 Hz",
    "		VFO list: Sub Main MEM ",
    "		Mode list: AM PKTAM ",
    "		Antenna list: ANT1 ANT2 ",
    "		Low power: 1 W, High power: 30 W",
    "	24890000 Hz - 24990000 Hz",
    "		VFO list: Sub Main MEM ",
    "		Mode list: AM PKTAM ",
    "		Antenna list: ANT1 ANT2 ",
    "		Low power: 1 W, High power: 30 W",
    "	28000000 Hz - 29700000 Hz",
    "		VFO list: Sub Main MEM ",
    "		Mode list: AM PKTAM ",
    "		Antenna list: ANT1 ANT2 ",
    "		Low power: 1 W, High power: 30 W",
    "	50000000 Hz - 54000000 Hz",
    "		VFO list: Sub Main MEM ",
    "		Mode list: AM PKTAM ",
    "		Antenna list: ANT1 ANT2 ",
    "		Low power: 1 W, High power: 30 W",
    "	5330500 Hz - 5333500 Hz",
    "		VFO list: Sub Main MEM ",
    "		Mode list: AM CW USB LSB RTTY FM CWR RTTYR PKTLSB PKTUSB PKTFM PSK PSKR ",
    "		Antenna list: ANT1 ANT2 ",
    "		Low power: 2 W, High power: 100 W",
    "	5346500 Hz - 5349500 Hz",
    "		VFO list: Sub Main MEM ",
    "		Mode list: AM CW USB LSB RTTY FM CWR RTTYR PKTLSB PKTUSB PKTFM PSK PSKR ",
    "		Antenna list: ANT1 ANT2 ",
    "		Low power: 2 W, High power: 100 W",
    "	5366500 Hz - 5369500 Hz",
    "		VFO list: Sub Main MEM ",
    "		Mode list: AM CW USB LSB RTTY FM CWR RTTYR PKTLSB PKTUSB PKTFM PSK PSKR ",
    "		Antenna list: ANT1 ANT2 ",
    "		Low power: 2 W, High power: 100 W",
    "	5371500 Hz - 5374500 Hz",
    "		VFO list: Sub Main MEM ",
    "		Mode list: AM CW USB LSB RTTY FM CWR RTTYR PKTLSB PKTUSB PKTFM PSK PSKR ",
    "		Antenna list: ANT1 ANT2 ",
    "		Low power: 2 W, High power: 100 W",
    "	5403500 Hz - 5406500 Hz",
    "		VFO list: Sub Main MEM ",
    "		Mode list: AM CW USB LSB RTTY FM CWR RTTYR PKTLSB PKTUSB PKTFM PSK PSKR ",
    "		Antenna list: ANT1 ANT2 ",
    "		Low power: 2 W, High power: 100 W",
    "RX ranges #2 for TBD:",
    "	30000 Hz - 60000000 Hz",
    "		VFO list: Sub Main MEM ",
    "		Mode list: AM CW USB LSB RTTY FM CWR RTTYR PKTLSB PKTUSB PKTFM PKTAM PSK PSKR ",
    "		Antenna list: ANT1 ANT2 ",
    "TX ranges #3 for TBD:",
    "RX ranges #3 for TBD:",
    "TX ranges #4 for TBD:",
    "RX ranges #4 for TBD:",
    "TX ranges #5 for TBD:",
    "RX ranges #5 for TBD:",
    "TX ranges #1 status for ITU1:	OK (0)",
    "RX ranges #1 status for TBD:	OK (0)",
    "TX ranges #2 status for TBD:	OK (0)",
    "RX ranges #2 status for TBD:	OK (0)",
    "TX ranges #3 status for TBD:	OK (0)",
    "RX ranges #3 status for TBD:	OK (0)",
    "TX ranges #4 status for TBD:	OK (0)",
    "RX ranges #4 status for TBD:	OK (0)",
    "TX ranges #5 status for TBD:	OK (0)",
    "RX ranges #5 status for TBD:	OK (0)",
    "Tuning steps:",
    "	1 Hz:   	AM CW USB LSB RTTY FM CWR RTTYR PKTLSB PKTUSB PKTFM PKTAM PSK PSKR ",
    "	100 Hz:   	AM CW USB LSB RTTY FM CWR RTTYR PKTLSB PKTUSB PKTFM PKTAM PSK PSKR ",
    "	1 kHz:   	AM CW USB LSB RTTY FM CWR RTTYR PKTLSB PKTUSB PKTFM PKTAM PSK PSKR ",
    "	5 kHz:   	AM CW USB LSB RTTY FM CWR RTTYR PKTLSB PKTUSB PKTFM PKTAM PSK PSKR ",
    "	9 kHz:   	AM CW USB LSB RTTY FM CWR RTTYR PKTLSB PKTUSB PKTFM PKTAM PSK PSKR ",
    "	10 kHz:   	AM CW USB LSB RTTY FM CWR RTTYR PKTLSB PKTUSB PKTFM PKTAM PSK PSKR ",
    "	12.5 kHz:   	AM CW USB LSB RTTY FM CWR RTTYR PKTLSB PKTUSB PKTFM PKTAM PSK PSKR ",
    "	20 kHz:   	AM CW USB LSB RTTY FM CWR RTTYR PKTLSB PKTUSB PKTFM PKTAM PSK PSKR ",
    "	25 kHz:   	AM CW USB LSB RTTY FM CWR RTTYR PKTLSB PKTUSB PKTFM PKTAM PSK PSKR ",
    "Tuning steps status:	OK (0)",
    "Filters:",
    "	2.4 kHz:   	USB LSB PKTLSB PKTUSB ",
    "	1.8 kHz:   	USB LSB PKTLSB PKTUSB ",
    "	3 kHz:   	USB LSB PKTLSB PKTUSB ",
    "	500 Hz:   	CW RTTY CWR RTTYR PSK PSKR ",
    "	250 Hz:   	CW RTTY CWR RTTYR PSK PSKR ",
    "	1.2 kHz:   	CW CWR PSK PSKR ",
    "	2.4 kHz:   	RTTY RTTYR ",
    "	6 kHz:   	AM PKTAM ",
    "	3 kHz:   	AM PKTAM ",
    "	9 kHz:   	AM PKTAM ",
    "	10 kHz:   	FM PKTFM ",
    "	7 kHz:   	FM PKTFM ",
    "	15 kHz:   	FM PKTFM ",
    "Bandwidths:",
    "	AM	Normal: 6 kHz,	Narrow: 3 kHz,	Wide: 9 kHz",
    "	CW	Normal: 500 Hz,	Narrow: 250 Hz,	Wide: 1.2 kHz",
    "	USB	Normal: 2.4 kHz,	Narrow: 1.8 kHz,	Wide: 3 kHz",
    "	LSB	Normal: 2.4 kHz,	Narrow: 1.8 kHz,	Wide: 3 kHz",
    "	RTTY	Normal: 500 Hz,	Narrow: 250 Hz,	Wide: 2.4 kHz",
    "	FM	Normal: 10 kHz,	Narrow: 7 kHz,	Wide: 15 kHz",
    "	CWR	Normal: 500 Hz,	Narrow: 250 Hz,	Wide: 1.2 kHz",
    "	RTTYR	Normal: 500 Hz,	Narrow: 250 Hz,	Wide: 2.4 kHz",
    "	PKTLSB	Normal: 2.4 kHz,	Narrow: 1.8 kHz,	Wide: 3 kHz",
    "	PKTUSB	Normal: 2.4 kHz,	Narrow: 1.8 kHz,	Wide: 3 kHz",
    "	PKTFM	Normal: 10 kHz,	Narrow: 7 kHz,	Wide: 15 kHz",
    "	PKTAM	Normal: 6 kHz,	Narrow: 3 kHz,	Wide: 9 kHz",
    "	PSK	Normal: 500 Hz,	Narrow: 250 Hz,	Wide: 1.2 kHz",
    "Has priv data:	Y",
    "Has Init:	Y",
    "Has Cleanup:	Y",
    "Has Open:	Y",
    "Has Close:	Y",
    "Can set Conf:	Y",
    "Can get Conf:	Y",
    "Can set Frequency:	Y",
    "Can get Frequency:	Y",
    "Can set Mode:	Y",
    "Can get Mode:	Y",
    "Can set VFO:	Y",
    "Can get VFO:	N",
    "Can set PTT:	Y",
    "Can get PTT:	Y",
    "Can get DCD:	Y",
    "Can set Repeater Duplex:	N",
    "Can get Repeater Duplex:	N",
    "Can set Repeater Offset:	N",
    "Can get Repeater Offset:	N",
    "Can set Split Freq:	Y",
    "Can get Split Freq:	Y",
    "Can set Split Mode:	Y",
    "Can get Split Mode:	Y",
    "Can set Split VFO:	Y",
    "Can get Split VFO:	Y",
    "Can set Tuning Step:	Y",
    "Can get Tuning Step:	Y",
    "Can set RIT:	Y",
    "Can get RIT:	Y",
    "Can set XIT:	Y",
    "Can get XIT:	Y",
    "Can set CTCSS:	Y",
    "Can get CTCSS:	Y",
    "Can set DCS:	N",
    "Can get DCS:	N",
    "Can set CTCSS Squelch:	Y",
    "Can get CTCSS Squelch:	Y",
    "Can set DCS Squelch:	N",
    "Can get DCS Squelch:	N",
    "Can set Power Stat:	Y",
    "Can get Power Stat:	Y",
    "Can Reset:	N",
    "Can get Ant:	Y",
    "Can set Ant:	Y",
    "Can set Transceive:	E",
    "Can get Transceive:	N",
    "Can set Func:	Y",
    "Can get Func:	Y",
    "Can set Level:	Y",
    "Can get Level:	Y",
    "Can set Param:	Y",
    "Can get Param:	Y",
    "Can send DTMF:	N",
    "Can recv DTMF:	N",
    "Can send Morse:	N",
    "Can send Voice:	N",
    "Can decode Events:	Y",
    "Can set Bank:	N",
    "Can set Mem:	Y",
    "Can get Mem:	N",
    "Can set Channel:	E",
    "Can get Channel:	E",
    "Can ctl Mem/VFO:	Y",
    "Can Scan:	Y",
    "Can get Info:	N",
    "Can get power2mW:	N",
    "Can get mW2power:	N"
  )
  val data: Map[String, Seq[String]] = {
    Seq(
      ("f", Seq("7074000")),
      ("1", expectedCaps),
    ).toMap
  }


}